project:
  type: default
  output-dir: _output
  render:
    - manuscript.qmd
    - supplementary.qmd

format:
  pdf:
    documentclass: article
    number-sections: true
    colorlinks: true
    geometry: margin=2.5cm
  docx: default

bibliography: references.bib
csl: nature.csl
